includes:
  dev:
    - test

dev:
  apt:
    - libxml2-dev
    - libxslt1-dev

  pip:
    - check-manifest
    - coverage
    - detox
    - fmap
    - ipdb
    - ipdbplugin
    - ipython
    - lxml
    - mock
    - nose
    - pip-tools
    - Sphinx
    - twine
    - tox
    - xunitmerge

test:
  pip:
    - mock

prod:
  pip:
    - dockerman
    - requests
